<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" PrivateAssets="all" />
    <PackageReference Include="NUnit.Analyzers" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Toren.App/Toren.App.csproj" />
    <ProjectReference Include="../../src/Toren.Containers/Toren.Containers.csproj" />
    <ProjectReference Include="../../src/Toren.Core/Toren.Core.csproj" />
    <ProjectReference Include="../../src/Toren.Debugging/Toren.Debugging.csproj" />
    <ProjectReference Include="../../src/Toren.DotNet/Toren.DotNet.csproj" />
    <ProjectReference Include="../../src/Toren.Git/Toren.Git.csproj" />
    <ProjectReference Include="../../src/Toren.Language/Toren.Language.csproj" />
    <ProjectReference Include="../../src/Toren.Workspaces/Toren.Workspaces.csproj" />
  </ItemGroup>
</Project>
