<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.AvaloniaEdit" />
    <PackageReference Include="AvaloniaEdit.TextMate" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Toren.Debugging/Toren.Debugging.csproj" />
    <ProjectReference Include="../Toren.DotNet/Toren.DotNet.csproj" />
    <ProjectReference Include="../Toren.Git/Toren.Git.csproj" />
    <ProjectReference Include="../Toren.Language/Toren.Language.csproj" />
    <ProjectReference Include="../Toren.Platform/Toren.Platform.csproj" />
    <ProjectReference Include="../Toren.Workspaces/Toren.Workspaces.csproj" />
  </ItemGroup>
</Project>
